version: '3'

services:
  pf_api:
    build: ./server
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: pf_api
    ports:
      - "8000:8000"

  pf_web:
    build: ./client
    command: npm start
    container_name: pf_web
    ports:
      - "80:8080"